---
title: "Here are some plotly plots"
output: 
  html_document
---

Interactivity is great!

Here's the tidyverse.
```{r, message = FALSE}
library(tidyverse)
library(plotly)

library(p8105.datasets)
```

Let's load the AirBnB dataset.

```{r}
data("nyc_airbnb")

nyc_airbnb =
  nyc_airbnb |> 
  mutate(
    rating = review_scores_location / 2
  ) |> 
  select(
    neighbourhood_group, neighbourhood, rating,
    price, room_type, lat, long
  ) |> 
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price <= 500,
    price >= 100
  )
```


Let's make a scatterplot!!!! But interactive this time

```{r}
nyc_airbnb |> 
  mutate(
    label = str_c("Price: $", price, "Rating:", rating)
  ) |> 
  plot_ly(
    x = ~lat, y = ~long, color = ~price,
    text = ~label,
    type = "scatter", mode = "markers", alpha = 0.5
  )
```
"mode = line" if you want to do a scatter plot with lines connecting it. 


Let's make a boxplot.

```{r}
nyc_airbnb |> 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, price)
  ) |> 
  plot_ly(
    x = ~neighbourhood, y = ~price, color = ~neighbourhood,
    type = "box", colors = "viridis"
  )
```

Maybe barcharts next?

```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, n)
  ) |> 
  plot_ly(x = ~neighbourhood, y = ~n,
          type = "bar")
```








